config/routes.rb
DesignYou::Application.routes.draw do

  resources :style_sheets do
    member do
      put 'toggle'
    end
  end

  devise_for :users
  resources :users, except: [:new, :create, :destroy] do
    resources :messages
  end

  resources :assets, path: "/files" do
    collection do
      post "drag_upload"
    end
  end

  root to: "users#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :name, :read

  scope :unread, where(read: false)
  scope :recent, order('id DESC')

  validates :name, :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :find_user, only: [:new, :create]
  before_filter :authenticate_user!, only: [:index, :destroy]
  # GET /messages
  # GET /messages.json
  def index
    @messages = current_user.messages.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
    @message.update_attribute(:read, true)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = @user.messages.build(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to user_path(@user), notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = current_user.messages.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  def find_user
    @user = User.find(params[:user_id].to_i)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper

  def read_icon(is_read)
    klass = is_read ? "icon-ok" : "icon-remove"
    raw content_tag :i, nil, { class: klass }
  end
end

app/views/messages/_form.html.erb
<%= simple_form_for([@user, @message], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, hint: "Your name" %>
    <%= f.input :content, as: :text, input_html: { rows: 8, class: 'span5' }, hint: "Max: 500 characters" %>
  </div>
  <div class="form-actions">
    <%= f.submit("Submit", { class: 'btn btn-primary' }) %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="span12">
  <div class="row">
    <div class="span12">
      <header>
        <h1>Messages</h1>
        <p><%= link_to("Back", user_path(current_user), { class: 'btn btn-primary' }) %></p>
      </header>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <table class="table table-striped">
        <tr>
          <th>Read</th>
          <th>Name</th>
          <th>Content</th>
          <th></th>
        </tr>

      <% @messages.each do |message| %>
        <tr>
          <td><%= read_icon(message.read?) %></td>
          <td><%= link_to(message.name, user_message_path(current_user, message)) %></td>
          <td><%= truncate(strip_tags(message.content), length: 100) %></td>
          <td><%= link_to 'Destroy', user_message_path(current_user, message), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<div class="span12">
  <div class="row">
    <div class="span12">
      <header>
        <h1>New message</h1>
        <p><%= link_to 'Back', user_path(@user), { class: 'btn btn-danger' } %></p>
      </header>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="span12">
  <p><%= link_to 'Back', user_messages_path(current_user), { class: 'btn btn-primary' } %></p>
  <p id="notice"><%= notice %></p>

  <p>
    <b>Name:</b>
    <%= @message.name %>
  </p>

  <p>
    <b>Content:</b>
    <%= @message.content %>
  </p>
</div>