config/routes.rb
DesignYou::Application.routes.draw do

  resources :style_sheets do
    member do
      put 'toggle'
    end
  end

  devise_for :users
  resources :users, except: [:new, :create, :destroy] do
    resources :messages
  end

  resources :assets, path: "/files" do
    collection do
      post "drag_upload"
    end
  end

  root to: "users#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :nickname, :description
  # attr_accessible :title, :body

  has_many :assets
  has_many :stylesheets, class_name: StyleSheet
  has_many :messages
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update]

  def index
    @page_title = "List users"
    @users = User.all
    @assets = Asset.random(24)
  end

  def show
    @user = User.includes(:assets).find(params[:id].to_i)
    @stylesheet_file = @user.stylesheets.where({enabled: true}).first || nil
  end

  def edit
    @user = current_user
    @style_sheets = @user.stylesheets || []
    @messages = @user.messages.unread.recent.limit(6)
  end

  def update
    @user = current_user
    @style_sheets = @user.stylesheets || []
    @messages = @user.messages.unread.recent.limit(6)

    asset = params[:user].delete(:asset)
    @user.assets.build({asset: asset}) if asset

    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def authorized_area(user)
    yield if user_signed_in? && user === current_user
  end
end

app/views/users/edit.html.erb
<div class="span12">
  <div class="row">
    <div class="span12">
      <header>
        <h1 id="user-name">
          Edit your account
        </h1>
        <p class="pull-right">
          <div class="pull-right">
            <% if user_signed_in? %>
              <p>Hello! <%= link_to(current_user.nickname, user_path(current_user)) %> [ <%= link_to('Sign out', destroy_user_session_path, {method: :delete}) %> ]</p>
            <% else %>
              <%= link_to('Sign Up', new_user_registration_path) %> | <%= link_to('Sign In', new_user_session_path) %>
            <% end %>
          </div>
        </p>
      </header>
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <%= simple_form_for @user, html: { class: 'form-horizontal' } do |f| %>
        <div class="form-inputs">
          <%= field_set_tag "基本資訊" do %>
            <%= f.input :nickname, { label: 'Name', hint: "您可以在這裡寫上您的真實姓名、暱稱或者工作室名稱" } %>
            <%= f.input :description, { as: :text, label: "介紹", hint: "來一點自我介紹(請不要寫上作品介紹)吧？", input_html: { class: 'span4', rows: 8 } } %>
          <% end %>
          <fieldset>
            <legend>上傳您的作品 <small data-toggle="modal" data-target="myModal">(如何上傳作品？)</small></legend>
            <%= f.input :asset, { as: :file, label: "請選擇檔案", hint: "只允許JPG/PNG/TIFF/GIF格式，並且小於3MB" } %>
          </fieldset>
        </div>
        <div class="form-actions">
          <%= f.submit("Submit", { class: 'btn' }) %>
          <%= link_to("Cancel", user_path(current_user), { class: 'btn btn-danger' }) %>
        </div>
      <% end %>
    </div>
    <div class="span6">
      <div class="row">
        <div class="span6">
          <h3>Messages</h3>
          <% if @messages.blank? %>
            <p>目前沒有任何新留言</p>
          <% else %>
            <table>
              <thead>
                <tr>
                  <td>作者</td>
                  <td>日期</td>
                </tr>
              </thead>
              <tbody>
                <% @messages.each do |message| %>
                  <tr>
                    <td><%= link_to(message.name, user_message_path(current_user, message)) %></td>
                    <td><%= message.created_at %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
        <div class="span6">
          <h3>自定樣板 (自行撰寫CSS設計)</h3>
          <p><small><%= link_to("建立新的樣板", new_style_sheet_path) %></small></p>
          <table class="table">
            <thead>
              <tr>
                <td>id</td>
                <td>啟用中</td>
                <td>名稱</td>
              </tr>
            </thead>
            <tbody>
              <% @style_sheets.each do |css| %>
                <tr>
                  <td><%= css.id %></td>
                  <td><%= link_to((css.enabled? ? "啟用" : "不啟用"), toggle_style_sheet_path(css), { method: :put }) %></td>
                  <td><%= link_to(css.name, edit_style_sheet_path(css)) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">如何上傳作品？</h3>
  </div>
  <div class="modal-body">
    <p>可以直接從「檔案總管」或者是「Finder」中將您的作品拖到網頁上後放開就會自動上傳。</p>
    <p>也可以在下方的上傳作品中手動選擇檔案後按下Submit來上傳。</p>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">瞭解了</button>
  </div>
</div>

app/views/users/index.html.erb
<div class="span12">
  <div class="row">
    <header class="span10 offset1">
      <h1 id="user-name">Design You</h1>
      <small id="slogan">Show your works, get the chance!</small>
      <% if user_signed_in? && current_user.nickname.blank? %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Warning!</strong> 你還沒有設定你的名字哦！快到 <%= link_to("個人頁面", user_path(current_user)) %> 內設定吧！
        </div>
      <% end %>
      <div>
        <div class="pull-right">
          <% if user_signed_in? %>
            <p>Hello! <%= link_to(current_user.nickname, user_path(current_user)) %> [ <%= link_to("登出", destroy_user_session_path, {method: :delete}) %> ]</p>
          <% else %>
            <%= link_to("註冊", new_user_registration_path) %> | <%= link_to("登入", new_user_session_path) %>
          <% end %>
        </div>
      </div>
    </header>
  </div>
  <div class="row">
    <div class="row">
      <hr class="span10 offset1" />
      <div id="description" class="span10 offset1">
        <p>Upload your works today and show them to your friends or get hire!</p>
      </div>
      <div id="images" class="span10 offset2">
        <ul class="thumbnails">
          <% @assets.each do |asset| %>
            <li class="span4 offset2 card-container">
              <div class="card">
                <div class="back">
                  <h3><%= asset.user.nickname %></h3>
                  <p class="description"><%= truncate(strip_tags(asset.user.description), length: 250) %></p>
                  <p><%= link_to("Show more", user_path(asset.user)) %></p>
                </div>
                <div class="front"><%= image_tag(asset.asset.url(:thumb)) %></div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="span12">
  <div class="row">
    <header class="span10 offset1">
      <h1 id="user-name">
        <%= @user.nickname %>
      </h1>
      <p>
        <%= link_to("回首頁", root_path) %>
        <% authorized_area(@user) do %>
          <small class="editable"> | <%= link_to("Edit your profile", edit_user_path(current_user)) %></small>
        <% end %>
      </p>
      <p class="pull-right">
        <div class="pull-right">
          <% if user_signed_in? %>
            <p>Hello! <%= link_to(current_user.nickname, user_path(current_user)) %> [ <%= link_to('Sign out', destroy_user_session_path, {method: :delete}) %> ]</p>
          <% else %>
            <p><%= link_to('Sign Up', new_user_registration_path) %> | <%= link_to('Sign In', new_user_session_path) %></p>
          <% end %>
          <p><%= link_to("Leave message", new_user_message_path(@user)) %></p>
        </div>
      </p>
    </header>
  </div>
  <div class="row">
    <hr class="span10 offset1" />
    <div id="description" class="span10 offset1">
      <blockquote><%= @user.description %></blockquote>
    </div>
    <div id="images" class="span10 offset1">
      <ul class="unstyled">
        <% @user.assets.each do |asset| %>
          <li class="box">
            <%= image_tag(asset.asset.url) %>
            <% authorized_area(@user) do %>
              <p><%= link_to("刪除此作品", asset_path(asset), { confirm: "確定真的要刪除嗎？", method: :delete }) %></p>
            <% end %>
          </li>
        <% end %>
        <li><small><%= link_to("回首頁", root_path) %></small></li>
      </ul>
    </div>
  </div>
</div>



<% content_for :css_area do %>
  <%= stylesheet_link_tag(style_sheet_path(@stylesheet_file, { format: 'css' })) if @stylesheet_file %>
<% end %>