config/routes.rb
DesignYou::Application.routes.draw do

  resources :style_sheets do
    member do
      put 'toggle'
    end
  end

  devise_for :users
  resources :users, except: [:new, :create, :destroy] do
    resources :messages
  end

  resources :assets, path: "/files" do
    collection do
      post "drag_upload"
    end
  end

  root to: "users#index"

end

app/models/style_sheet.rb
class StyleSheet < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :content
end

app/controllers/style_sheets_controller.rb
class StyleSheetsController < ApplicationController
  before_filter :authenticate_user!
  # GET /style_sheets
  # GET /style_sheets.json
  def index
    @style_sheets = current_user.stylesheets.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @style_sheets }
    end
  end

  # GET /style_sheets/1
  # GET /style_sheets/1.json
  def show
    @style_sheet = current_user.stylesheets.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.css {
        render text: @style_sheet.content
      }
      format.json { render json: @style_sheet }
    end
  end

  # GET /style_sheets/new
  # GET /style_sheets/new.json
  def new
    @style_sheet = current_user.stylesheets.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @style_sheet }
    end
  end

  # GET /style_sheets/1/edit
  def edit
    @style_sheet = current_user.stylesheets.find(params[:id])
  end

  # POST /style_sheets
  # POST /style_sheets.json
  def create
    @style_sheet = current_user.stylesheets.build(params[:style_sheet])

    respond_to do |format|
      if @style_sheet.save
        format.html { redirect_to edit_user_path(current_user), notice: 'Style sheet was successfully created.' }
        format.json { render json: @style_sheet, status: :created, location: @style_sheet }
      else
        format.html { render action: "new" }
        format.json { render json: @style_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /style_sheets/1
  # PUT /style_sheets/1.json
  def update
    @style_sheet = current_user.stylesheets.find(params[:id])

    respond_to do |format|
      if @style_sheet.update_attributes(params[:style_sheet])
        format.html { redirect_to edit_user_path(current_user), notice: 'Style sheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @style_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /style_sheets/1
  # DELETE /style_sheets/1.json
  def destroy
    @style_sheet = current_user.stylesheets.find(params[:id])
    @style_sheet.destroy

    respond_to do |format|
      format.html { redirect_to style_sheets_url }
      format.json { head :no_content }
    end
  end

  def toggle
    css = StyleSheet.find(params[:id])
    current_state = css.enabled
    ActiveRecord::Base.connection.execute("UPDATE `style_sheets` SET `style_sheets`.`enabled` = 0")
    css.update_attribute(:enabled, !current_state)

    redirect_to edit_user_path(current_user)
  end
end

app/helpers/style_sheets_helper.rb
module StyleSheetsHelper
end

app/views/style_sheets/_form.html.erb
<%= simple_form_for(@style_sheet, html: {class: 'form-horizontal'}) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :content, as: :text, input_html: {class: 'span6'} %>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/style_sheets/edit.html.erb
<div class="row">
  <div class="span12">
    <div class="row">
      <div class="span8">
        <%= render 'form' %>
      </div>
      <div class="span4">
        <h1>樣板元素的CSS Selector</h1>
        <hr />
        <dl>
          <dt>標題/名稱</dt>
          <dd><code>.users-controller.show-action header #user-name</code></dd>
          <dt>簡介文字</dt>
          <dd><code>#description</code></dd>
          <dt>圖片列表</dt>
          <dd><code>.users-controller.show-action #images</code></dd>
          <dt>圖片</dt>
          <dd><code>.users-controller.show-action #images ul .box</code></dd>
          <dt>範例</dt>
          <dd>
            <pre>
#user-name {
  color: red;
}

#description{
  color: green;
}

.users-controller.show-action #images ul li.box{
  margin-bottom: 200px;
}
            </pre>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>

app/views/style_sheets/index.html.erb
<div class="row">
  <div class="span12">
    <header>
      <h1>樣式表</h1>
      <p><%= link_to "新增一個樣式", new_style_sheet_path, {class: 'btn btn-primary'} %></p>
    </header>
  </div>
</div>
<div class="row">
  <div class="span12">

    <table>
      <tr>
        <th>User</th>
        <th>Content</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @style_sheets.each do |style_sheet| %>
      <tr>
        <td><%= style_sheet.user %></td>
        <td><%= style_sheet.content %></td>
        <td><%= link_to 'Show', style_sheet %></td>
        <td><%= link_to 'Edit', edit_style_sheet_path(style_sheet) %></td>
        <td><%= link_to 'Destroy', style_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />


  </div>
</div>

app/views/style_sheets/new.html.erb
<div class="row">
  <div class="span12">
    <div class="row">
      <div class="span8">
        <%= render 'form' %>
      </div>
      <div class="span4">
        <h1>樣板元素的CSS Selector</h1>
        <hr />
        <dl>
          <dt>標題/名稱</dt>
          <dd><code>.users-controller.show-action header #user-name</code></dd>
          <dt>簡介文字</dt>
          <dd><code>#description</code></dd>
          <dt>圖片列表</dt>
          <dd><code>.users-controller.show-action #images</code></dd>
          <dt>圖片</dt>
          <dd><code>.users-controller.show-action #images ul .box</code></dd>
          <dt>範例</dt>
          <dd>
            <pre>
#user-name {
  color: red;
}

#description{
  color: green;
}

.users-controller.show-action #images ul li.box{
  margin-bottom: 200px;
}
            </pre>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>

app/views/style_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @style_sheet.user %>
</p>

<p>
  <b>Content:</b>
  <%= @style_sheet.content %>
</p>


<%= link_to 'Edit', edit_style_sheet_path(@style_sheet) %> |
<%= link_to 'Back', style_sheets_path %>